version: "3.6"

services:
  frontend:
    ports:
      - "8710:8080"
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/latest/demo
  docusaurus:
    ports:
      - "8711:80"
  storybook:
    ports:
      - "8712:80"
